image: node:latest

stages:
  - build
  - deploy


buildApp:
  stage: build
  image: golang:latest
  before_script:
    - apt-get update -y
    - apt-get install zip -y
    - cd $GOPATH/src
    - mkdir -p gitlab.com/$CI_PROJECT_NAMESPACE
    - cd gitlab.com/$CI_PROJECT_NAMESPACE
    - ln -s $CI_PROJECT_DIR
    - cd $CI_PROJECT_NAME
    - go get -u github.com/golang/dep/cmd/dep
  script:
    - make build
  artifacts:
    when: on_success
    paths:
      - bin


production:
  stage: deploy
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
  script:
    - serverless deploy --stage production --verbose
  environment: production
  dependencies:
    - buildApp
  only:
    refs:
      - master

